"""
Example DAG: Email Service & Notifier
=====================================
Bu DAG, `citadel.notifications.email` modülündeki:
- `EmailService` (HTML formatında e-posta raporu gönderme)
- `EmailNotifier` (Task veya DAG fail olduğunda otomatik bildirim gönderme callback'i)
kullanımını gösterir.

Ne zaman kullanılır?
--------------------
- Ingestion, ETL veya analiz sonuçlarını HTML tablo ve özetlerle ekibe göndermek için
- Kritik pipeline'lar hata aldığında otomatik uyarı maili tetiklemek için

Kullanılan Servis:
------------------
- `citadel.notifications.email.EmailService`
- `citadel.notifications.email.EmailNotifier`
- `citadel.config_loader.config`
"""

from datetime import timedelta
import pendulum
from airflow.decorators import dag, task

from citadel.config_loader import config
from citadel.notifications.email import EmailNotifier, EmailService

# 1. EmailNotifier Callback Tanımlaması
# DAG veya task fail olursa bu callback otomatik tetiklenir
failure_callback = EmailNotifier(
    to_email=config.notifications.get("default_to", ["obasekin@arcanor.com"]),
    conn_id=config.notifications.get("smtp_conn_id", "smtp_default"),
)

default_args = {
    "owner": "obasekin",
    "retries": 1,
    "retry_delay": timedelta(minutes=2),
    "on_failure_callback": failure_callback,  # Task seviyesi hata bildirimi
}

@dag(
    dag_id="example_citadel_email_service",
    default_args=default_args,
    start_date=pendulum.datetime(2026, 1, 1, tz="Europe/Istanbul"),
    schedule=None,  # Manuel tetiklemeli örnek DAG
    catchup=False,
    tags=["example", "citadel", "email", "notifications"],
    description="Citadel EmailService ve EmailNotifier kullanım örneği",
)
def example_email_service_workflow():

    @task(task_id="send_html_report_email")
    def send_report(**kwargs) -> str:
        """
        EmailService kullanarak zengin HTML formatında bir e-posta gönderir.
        """
        logical_date = kwargs.get("logical_date", pendulum.now())
        date_str = logical_date.strftime("%Y-%m-%d %H:%M")

        # HTML içeriği hazırlıyoruz (stil ve tablolar desteklenir)
        html_content = f"""
        <html>
        <body style="font-family: Arial, sans-serif; color: #333;">
            <h2 style="color: #2c3e50;">Daily Ingestion & Analysis Summary</h2>
            <p>Execution Time: <b>{date_str}</b></p>
            
            <table border="1" cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%;">
                <tr style="background-color: #34495e; color: white;">
                    <th>Country</th>
                    <th>Status</th>
                    <th>Records Ingested</th>
                    <th>Duration</th>
                </tr>
                <tr>
                    <td>TUR</td>
                    <td style="color: green; font-weight: bold;">SUCCESS</td>
                    <td>1,250,400</td>
                    <td>12m 30s</td>
                </tr>
                <tr style="background-color: #f9f9f9;">
                    <td>BEL</td>
                    <td style="color: green; font-weight: bold;">SUCCESS</td>
                    <td>850,200</td>
                    <td>8m 15s</td>
                </tr>
                <tr>
                    <td>NLD</td>
                    <td style="color: green; font-weight: bold;">SUCCESS</td>
                    <td>940,100</td>
                    <td>9m 45s</td>
                </tr>
            </table>
            
            <br>
            <p style="font-size: 12px; color: #7f8c8d;">This email was automatically generated by Airflow Citadel EmailService.</p>
        </body>
        </html>
        """

        # EmailService örneği oluşturuyoruz
        service = EmailService(
            conn_id=config.notifications.get("smtp_conn_id", "smtp_default")
        )

        recipients = config.notifications.get("default_to", ["obasekin@arcanor.com"])
        subject = f"[Airflow Report] Daily Data Status - {date_str}"

        print(f"Sending email to: {recipients}")
        print(f"Subject: {subject}")

        # E-posta gönderimi
        service.send_email(
            to=recipients,
            subject=subject,
            html_content=html_content,
            cc="kkalle@arcanor.com",  # Opsiyonel CC adresi
        )

        return f"Email sent successfully to {recipients}"

    @task(task_id="log_completion")
    def log_done(status_msg: str):
        print(f"Workflow result: {status_msg}")

    status = send_report()
    log_done(status)


example_email_service_workflow()

